server:
  port: 8080
  servlet:
    encoding:
      force-response: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/likeliondb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true